language: node_js
node_js: "8"

before_install:
  - openssl aes-256-cbc -K $encrypted_8c393341f536_key -iv $encrypted_8c393341f536_iv -in gcs.json.enc -out gcs.json -d

deploy:
  - provider: gcs
    project_id: "tutor-204108"
    credentials: "gcs.json"
    bucket: tutor-info
    skip_cleanup: true
    acl: public-read
    cache_control: "max-age=3600"
    local-dir: "dist"
    on:
      branch: master
      tags: true
  - provider: gcs
    project_id: "tutor-204108"
    credentials: "gcs.json"
    bucket: tutor-info-test
    skip_cleanup: true
    acl: public-read
    cache_control: "max-age=3600"
    local-dir: "dist"
    on:
      branch: test