language: node_js
node_js: "8"

before_install:
  - openssl aes-256-cbc -K $encrypted_8c393341f536_key -iv $encrypted_8c393341f536_iv -in gcs.json.enc -out gcs.json -d
  - export GOOGLE_APPLICATION_CREDENTIALS=$(pwd)/gcs.json

deploy:
  - provider: script
    skip_cleanup: true
    script: gulp deploy --branch master
    on:
      branch: master
  - provider: script
    skip_cleanup: true
    script: gulp deploy --branch test
    on:
      branch: test